name: ✅ Path 3 - Classically Verifiable Problems Submission
description: Submit a problem solution for the Classically Verifiable pathway - When quantum outputs are hard to find but easy to check
title: "[Verifiable] "
labels: ["pathway: classically-verifiable", "submission"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✅ Path 3 - Classically Verifiable Problems Pathway

        Thank you for submitting a solution to the **Classically Verifiable Problems** pathway!

        This pathway focuses on solutions that are hard to generate classically but easy to verify. Your submission should demonstrate quantum generation with efficient classical verification.

        Please provide detailed information about your submission below.

  - type: input
    id: circuit
    attributes:
      label: Circuit
      description: The problem instance this submission addresses
      placeholder: e.g., "peaked_random_53"
    validations:
      required: true

  - type: input
    id: value
    attributes:
      label: Value
      description: The claimed value (hamming distance for peak circuits)
      placeholder: e.g., "0.0023"
    validations:
      required: true

  - type: input
    id: observable-value
    attributes:
      label: Observable Value
      description: Observable value measurement
      placeholder: e.g., "0.156"
    validations:
      required: false

  - type: textarea
    id: method
    attributes:
      label: Method
      description: Link to paper, code repository, or detailed explanation of the method (required for verification)
      placeholder: |
        Provide at least one of:
        - Paper/preprint: https://arxiv.org/abs/...
        - Code repository: https://github.com/...
        - Method explanation: Detailed description of the approach
    validations:
      required: true

  - type: input
    id: institution
    attributes:
      label: Institution
      description: Your institution or organization
      placeholder: e.g., "IBM Quantum"
    validations:
      required: true

  - type: input
    id: quantum-time
    attributes:
      label: Quantum Time (seconds)
      description: Quantum execution time in seconds
      placeholder: e.g., "5.2"
    validations:
      required: true

  - type: input
    id: classical-time
    attributes:
      label: Classical Time (seconds)
      description: Classical computation time in seconds
      placeholder: e.g., "9000"
    validations:
      required: false

  - type: input
    id: quantum-hardware
    attributes:
      label: Quantum Hardware
      description: Quantum hardware specification
      placeholder: e.g., "IBM Heron r2"
    validations:
      required: true

  - type: input
    id: classical-hardware
    attributes:
      label: Classical Hardware
      description: Classical hardware specification
      placeholder: e.g., "AMD EPYC 7763, 128 cores"
    validations:
      required: false

  - type: input
    id: submission-date
    attributes:
      label: Submission Date
      description: Date of submission (YYYY-MM-DD)
      placeholder: "2025-10-29"
    validations:
      required: true

  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      description: Verification checklist for Path 3 (answer scored against true solution)
      options:
        - label: Answer is scored against true solution
          required: true
        - label: Method documentation provided (paper/code/explanation)
          required: true
        - label: Results are reproducible
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        ### What happens next?

        Maintainers will review your submission for:
        - ✅ Reproducibility
        - ✅ Compliance with validation criteria (efficient verification)
        - ✅ Data fidelity and traceability
        - ✅ Transparent documentation of assumptions and uncertainties

        Thank you for contributing to Quantum Advantage Pathways! 🚀
