name: ⚛️ Variational Problems Submission
description: Submit a problem solution for the Variational Problems pathway - Certifiable quantum solutions via the variational principle
title: "[Variational] "
labels: ["pathway: variational-problems", "submission"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚛️ Variational Problems Pathway

        Thank you for submitting a solution to the **Variational Problems** pathway!

        This pathway focuses on guaranteed solution bounds and benchmarking against classical methods. Your submission should demonstrate variational bounds (energy values as upper bounds to true ground-state energy).

        Please provide detailed information about your submission below.

  - type: input
    id: circuit
    attributes:
      label: Circuit
      description: The problem instance this submission addresses
      placeholder: e.g., "lih_molecule"
    validations:
      required: true

  - type: input
    id: energy
    attributes:
      label: Energy
      description: The ground-state energy value (upper bound)
      placeholder: e.g., "-7.8823"
    validations:
      required: true

  - type: input
    id: bounds-low
    attributes:
      label: Bounds (Low)
      description: Lower error bound (optional, default -1 if not provided)
      placeholder: e.g., "-0.001"
    validations:
      required: false

  - type: input
    id: bounds-high
    attributes:
      label: Bounds (High)
      description: Upper error bound (optional, default +1 if not provided)
      placeholder: e.g., "+0.001"
    validations:
      required: false

  - type: textarea
    id: method
    attributes:
      label: Method
      description: Link to paper, code repository, or detailed explanation of the method (required for verification)
      placeholder: |
        Provide at least one of:
        - Paper/preprint: https://arxiv.org/abs/...
        - Code repository: https://github.com/...
        - Method explanation: Detailed description of the approach
    validations:
      required: true

  - type: input
    id: institution
    attributes:
      label: Institution
      description: Your institution or organization
      placeholder: e.g., "IBM Quantum"
    validations:
      required: true

  - type: input
    id: quantum-time
    attributes:
      label: Quantum Time (seconds)
      description: Quantum execution time in seconds
      placeholder: e.g., "5.2"
    validations:
      required: true

  - type: input
    id: classical-time
    attributes:
      label: Classical Time (seconds)
      description: Classical computation time in seconds
      placeholder: e.g., "9000"
    validations:
      required: false

  - type: input
    id: quantum-hardware
    attributes:
      label: Quantum Hardware
      description: Quantum hardware specification
      placeholder: e.g., "IBM Heron r2"
    validations:
      required: true

  - type: input
    id: classical-hardware
    attributes:
      label: Classical Hardware
      description: Classical hardware specification
      placeholder: e.g., "AMD EPYC 7763, 128 cores"
    validations:
      required: false

  - type: input
    id: submission-date
    attributes:
      label: Submission Date
      description: Date of submission (YYYY-MM-DD)
      placeholder: "2025-10-29"
    validations:
      required: true

  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      description: Verification checklist for Path 2 (method is variational)
      options:
        - label: Method is variational (energy is upper bound)
          required: true
        - label: Method documentation provided (paper/code/explanation)
          required: true
        - label: Results are reproducible
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        ### What happens next?

        Maintainers will review your submission for:
        - ✅ Reproducibility
        - ✅ Compliance with validation criteria (variational property)
        - ✅ Data fidelity and traceability
        - ✅ Transparent documentation of assumptions and uncertainties

        Thank you for contributing to Quantum Advantage Pathways! 🚀
